### ISSUE TITLE
Error with morse

### ISSUE THREAD

**Issue by bee-san** [Ciphey/enCiphey#1]
```
➜ python3 enciphey.py
Opened dickens
Split file
My father’s family name being Pirrip, and my Christian name Philip, my
infant tongue could make of b
Self.text is ['My father’s family name being Pirrip, and my Christian name Philip, my\ninfant tongue could make of b']
Getting random sentence
Sents is now ['My father’s family name being Pirrip, and my Christian name Philip, my\ninfant tongue could make of b']
Sents is now ['My father’s family name being Pirrip, and my Christian name Philip, my\ninfant tongue could make of b', 'My father’s family name being Pirrip, and my Christian name Philip, my\ninfant tongue could make of b']
*********************8 My father’s family name being Pirrip, and my Christian name Philip, my
infant tongue could make of b. My father’s family name being Pirrip, and my Christian name Philip, my
infant tongue could make of b
Traceback (most recent call last):
  File "enciphey.py", line 47, in <module>
    print(obj.getRandomEncryptedSentence())
  File "enciphey.py", line 42, in getRandomEncryptedSentence
    sentsEncrypted = self.crypto.randomEncrypt(sents)
  File "/home/bee/Documents/enCiphey/src/encipher_crypto.py", line 33, in randomEncrypt
    encryptedText = func__use(text)
  File "/home/bee/Documents/enCiphey/src/encipher_crypto.py", line 137, in MorseCode
    return " ".join(MORSE_CODE_DICT.get(i.upper()) for i in text)
TypeError: sequence item 9: expected str instance, NoneType found
```

**Comment by bee-san** [comment]
This is because Morse code is old
